### PR TITLE
CHARTROOM_TEMPLATE

### PR DESCRIPTION
**Pull request by usamaidrsk**
### What it does?

- User is able to sign up if has no account.

- User then can  sign in.

- User is then directed to a chartBoard where  he views notifications of new messages, and charting side.
### What it does not do? 

- User is not yet able to receive or send message.

- Notifications cannot yet be received.

### CODE REVIEW

**Review by fahdjamy — COMMENTED** [review]
I think you have done a great job so far in terms of the UI, I guess things will be polished up in the future.

HOWEVER, the way code is written in not the right way of writing react.
I don't know when we can get time but if possible I would rather we have an online call you so that I show you the best practices of structuring and writing REACT.
I think there are just a few things that will be ironed out and then you'll be good to write React the most efficient way.

**Comment by fahdjamy** [comment]
Plus we will also work on using packages. I see you guys used bootstrap but not the best way.
we will go throw this.

**Comment by fahdjamy** [comment]
Plus, we will also have to review ways git best practices.
The commit message, the PR, git branching among others.

**Comment by fahdjamy** [comment]
I think @huxaiphaer will be merging this PR but after the call then you'll have to restructure the project just a little bit basing off of what we will talk about.

**Comment by usamaidrsk** [comment]
Thanks for the review and appreciation,
So then before we add any code we wait for the call

**Pull request merged**
