### PR TITLE
created the login using local storage

### PR DESCRIPTION
**Pull request by bdllhdrss3**
### **what it does**

- Sign up

- login

- store data using localstorage

### CODE REVIEW

**Comment by bdllhdrss3** [comment]
review this and merge usama

**Comment by usamaidrsk** [comment]
its not opening oba why

**Comment by usamaidrsk** [comment]
i've seen it, did u use the webstorm or the normal way to commit and push

**Review by usamaidrsk — COMMENTED** [review]
okay

**Pull request merged**
